name: nas2cloud
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  assets_audio_player: ^3.0.6
  connectivity_plus: ^3.0.2
  encrypt: ^5.0.1
  english_words: ^4.0.0
  event_bus: ^2.0.0
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  flutter_cached_pdfview: ^0.4.1
  flutter_downloader: ^1.10.1+2
  flutter_local_notifications: ^13.0.0
  flutter_uploader: ^3.0.0-beta.4
  http: ^0.13.5
  path: ^1.8.2
  path_provider: ^2.0.12
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  pointycastle: ^3.6.2
  provider: ^6.0.0
  shared_preferences: ^2.0.16
  sqflite: ^2.2.4+1
  url_launcher: ^6.1.8
  uuid: ^3.0.7
  video_player: ^2.5.0
  workmanager: ^0.5.1

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
