    docker run \
        --name nas2cloud \
        -p 8168:8168 \
        -v /Users/ZMS/Documents/ProjectBase/github/zhangms/nas2cloud/release/app:/nas2cloud/app \
        -v /Users/ZMS/Documents/ProjectBase/github/zhangms/nas2cloud/release/bin:/nas2cloud/bin \
        -v /Users/ZMS/Documents/ProjectBase/github/zhangms/nas2cloud/release/client:/nas2cloud/client \
        -v /Users/ZMS/Documents/ProjectBase/github/zhangms/nas2cloud/release/console:/nas2cloud/console \
        -v /Users/ZMS/Documents/ProjectBase/github/zhangms/nas2cloud/release/thumb:/nas2cloud/thumb \
        -v /Users/ZMS/Documents/ProjectBase/github/zhangms/nas2cloud/release/assets:/nas2cloud/assets \
        -v /Users/ZMS/Documents/ProjectBase/github/zhangms/nas2cloud/release/users:/nas2cloud/users \
        -v /Users/ZMS/Documents/ProjectBase/github/zhangms/nas2cloud/release/externals/Family:/nas2cloud/externals/Family \
        -d nas2cloud
