###
POST http://localhost:8080/api/store/walk
Content-Type: application/json
X-DEVICE: http-client
X-AUTH-TOKEN: zms-70cbb5a3-5d13-4769-a276-0c1593b59498

{
  "path": "/",
  "pageNo": 0,
  "pageSize": 50,
  "orderBy": "fileName"
}


###
GET http://localhost:8080/api/store/searchPhotoCount
Accept: application/json
X-DEVICE: http-client
X-AUTH-TOKEN: zms-ffa6b4c3-204e-4759-a8b0-a90314cbba44


###
POST http://localhost:8080/api/store/searchPhotos
Content-Type: application/json
X-DEVICE: http-client
X-AUTH-TOKEN: zms-ffa6b4c3-204e-4759-a8b0-a90314cbba44

{
  "searchAfter": "",
  "time": "2019-03"
}

