POST http://localhost:8080/api/store/walk
Content-Type: application/json
X-DEVICE: http-client
X-AUTH-TOKEN: zms-b8402d0a-10f8-433e-a376-067445f45406

{
  "path": "/",
  "pageNo": 0,
  "pageSize": 50,
  "orderBy": "fileName"
}

###
