POST http://localhost:8080/api/store/walk
Content-Type: application/json
X-DEVICE: http-client
X-AUTH-TOKEN: zms-4dcb6f77-246f-41b3-8749-1db3414592f3

{
  "path": "/Music",
  "pageNo": 0,
  "pageSize": 50,
  "orderBy": "fileName"
}

###
